
#Create list
foods = [
    {"name": "Burger 🍔", "price": 8.00},
    {"name": "Pizza 🍕", "price": 12.00},
    {"name": "Hot Dog 🌭", "price": 5.00},
    {"name": "French Fries 🍟", "price": 4.00},
    {"name": "Ice Cream 🍨", "price": 6.00},
    {"name": "Chocolate Cake 🍰", "price": 7.00},
    {"name": "Salad 🥗", "price": 6.00},
    {"name": "Tacos 🌮", "price": 9.00},
    {"name": "Pancakes 🥞", "price": 7.00},
    {"name": "Waffles 🧇", "price": 7.00},
    {"name": "Donut 🍩", "price": 2.00},
    {"name": "Popcorn 🍿", "price": 4.00},
    {"name": "Sandwich 🥪", "price": 6.00},
    {"name": "Fried Rice 🍚", "price": 9.00},
    {"name": "Ramen 🍜", "price": 12.00},
    {"name": "Cupcake 🧁", "price": 3.00},
    {"name": "Burrito 🌯", "price": 10.00},
    {"name": "Croissant 🥐", "price": 4.00},
    {"name": "Bagel 🥯", "price": 3.00},
    {"name": "Pretzel 🥨", "price": 3.00},
    {"name": "Eggs & Bacon 🍳", "price": 8.00},
    {"name": "Toast 🍞", "price": 2.00},
    {"name": "Cheese Plate 🧀", "price": 7.00},
    {"name": "Onion Rings 🧅", "price": 4.00},
    {"name": "Chicken Nuggets 🍗", "price": 5.00},
    {"name": "BBQ Ribs 🍖", "price": 14.00},
    {"name": "Dumplings 🥟", "price": 9.00},
    {"name": "Spring Rolls 🥢", "price": 6.00},
    {"name": "Kebab 🍢", "price": 10.00},
    {"name": "Mashed Potatoes 🥔", "price": 5.00},

    {"name": "Coffee ☕", "price": 3.00},
    {"name": "Orange Juice 🍊", "price": 4.00},
    {"name": "Soda 🥤", "price": 3.00},
    {"name": "Smoothie 🍓", "price": 5.00},
    {"name": "Energy Drink ⚡", "price": 4.00},
    {"name": "Water 💧", "price": 2.00},
    {"name": "Lemonade 🍋", "price": 4.00},
    {"name": "Tea 🍵", "price": 3.00},
    {"name": "Hot Chocolate 🍫", "price": 4.00},
    {"name": "Protein Shake 💪", "price": 6.00},
    {"name": "Coconut Water 🥥", "price": 5.00},
    {"name": "Apple Juice 🍎", "price": 4.00},
    {"name": "Grape Juice 🍇", "price": 4.00},
    {"name": "Mango Juice 🥭", "price": 5.00},
    {"name": "Milkshake 🍦", "price": 6.00},
]